version: '3.8'

services:
  conway-game-of-life:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: conway-game-of-life
    ports:
      - "8000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.conway.rule=Host(`localhost`)"
      - "traefik.http.services.conway.loadbalancer.server.port=80"
    networks:
      - conway-network

networks:
  conway-network:
    driver: bridge

# Дополнительный сервис для разработки (опционально)
# Раскомментируйте, если нужен dev режим
# conway-dev:
#   build:
#     context: .
#     dockerfile: Dockerfile.dev
#   container_name: conway-game-dev
#   ports:
#     - "5173:5173"
#   volumes:
#     - .:/app
#     - /app/node_modules
#   environment:
#     - NODE_ENV=development
#   command: npm run dev -- --host 0.0.0.0 